import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next dars | About",
  description: "Generated by create next app",
};

function Details({ params }: { params: { id: string } }) {
  return <div>{params.id}</div>;
}

export default Details;
